### ISSUE TITLE
Absolute path for filter now causes error

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#13]
If I use this min.yaml:

```yaml
templates:
  test:
    preprocessors: []
    pandoc:
      from: markdown
      to: html5
      standalone: true
      filter: /usr/local/bin/pandoc-citeproc
    postprocessors: []
```

and this min.md pandoc file:

```markdown
---  
title: "Minimal Test"
author: unknown
pandocomatic_:
  use-template: test
---  

# Summary #  

The background question is sound [@shipp2013], and of substantial importance for systems neuroscience [@clark2013].  

# References #

```

I get the following error. However if I don't specify the absolute path, i.e. `filter: pandoc-citeproc` then everything works fine.

```
👉  pandocomatic -c min.yaml -i min.md -o min.html
/Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/configuration.rb:200:in `update_path': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_command.rb:141:in `block in pandoc'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_command.rb:132:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_command.rb:132:in `pandoc'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_command.rb:92:in `convert_file'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_command.rb:59:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/command.rb:81:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_multiple_command.rb:81:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_multiple_command.rb:80:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/command/convert_file_multiple_command.rb:80:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/lib/pandocomatic/pandocomatic.rb:105:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pandocomatic-0.1.3/bin/pandocomatic:3:in `<top (required)>'
	from /usr/local/bin/pandocomatic:23:in `load'
	from /usr/local/bin/pandocomatic:23:in `<main>'
```

**Comment by htdebeer** [comment]
Fixed in version 0.1.3.2
