### ISSUE TITLE
Broken with Pandoc 2

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#28]
Note that Pandoc 2 has changed a few option names, for example `reference-[docx|odt]` is now `reference-doc`, `--smart` has been moved to an extension.

There is no ETA when Pandoc 2 will be released, but if in the interim pandocomatic could try to work with 1.X and 2.X it would be good. I think the issue is the hardcoded options with path in `convert_file_command.rb`, which could be updated to:

```
# TODO: update this list
    PANDOC_OPTIONS_WITH_PATH = [
      'filter', 
      'template', 
      'css', 
      'include-in-header', 
      'include-before-body',
      'include-after-body',
      'reference-odt',
      'reference-docx',
      'epub-stylesheet',
      'epub-cover-image',
      'epub-metadata',
      'epub-embed-font',
      'bibliography',
      'csl',
      'syntax-definition',
      'reference-doc',
      'lua-filter',
      'extract-media',
      'resource-path',
      'citation-abbreviations',
      'abbreviations',
      'log'
    ]
```

Here is the help from the latest Pandoc 2 nightly:

```
👉  pandoc --help
pandoc [OPTIONS] [FILES]
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT
  -o FILE               --output=FILE
                        --data-dir=DIRECTORY
                        --base-header-level=NUMBER
                        --indented-code-classes=STRING
  -F PROGRAM            --filter=PROGRAM
                        --lua-filter=SCRIPTPATH
  -p                    --preserve-tabs
                        --tab-stop=NUMBER
                        --track-changes=accept|reject|all
                        --file-scope
                        --extract-media=PATH
  -s                    --standalone
                        --template=FILE
  -M KEY[:VALUE]        --metadata=KEY[:VALUE]
  -V KEY[:VALUE]        --variable=KEY[:VALUE]
  -D FORMAT             --print-default-template=FORMAT
                        --print-default-data-file=FILE
                        --dpi=NUMBER
                        --eol=crlf|lf|native
                        --wrap=auto|none|preserve
                        --columns=NUMBER
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
                        --no-highlight
                        --highlight-style=STYLE
                        --syntax-definition=FILE
  -H FILE               --include-in-header=FILE
  -B FILE               --include-before-body=FILE
  -A FILE               --include-after-body=FILE
                        --resource-path=SEARCHPATH
                        --self-contained
                        --html-q-tags
                        --ascii
                        --reference-links
                        --reference-location=block|section|document
                        --atx-headers
                        --top-level-division=section|chapter|part
  -N                    --number-sections
                        --number-offset=NUMBERS
                        --listings
  -i                    --incremental
                        --slide-level=NUMBER
                        --section-divs
                        --default-image-extension=extension
                        --email-obfuscation=none|javascript|references
                        --id-prefix=STRING
  -T STRING             --title-prefix=STRING
  -c URL                --css=URL
                        --reference-doc=FILE
                        --epub-cover-image=FILE
                        --epub-metadata=FILE
                        --epub-embed-font=FILE
                        --epub-chapter-level=NUMBER
                        --latex-engine=PROGRAM
                        --latex-engine-opt=STRING
                        --bibliography=FILE
                        --csl=FILE
                        --citation-abbreviations=FILE
                        --natbib
                        --biblatex
  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]
                        --mathml
                        --mimetex[=URL]
                        --webtex[=URL]
                        --jsmath[=URL]
                        --mathjax[=URL]
                        --katex[=URL]
                        --katex-stylesheet=URL
                        --gladtex
                        --abbreviations=FILE
                        --trace
                        --dump-args
                        --ignore-args
                        --verbose
                        --quiet
                        --fail-if-warnings
                        --log=FILE
                        --bash-completion
                        --list-input-formats
                        --list-output-formats
                        --list-extensions
                        --list-highlight-languages
                        --list-highlight-styles
  -v                    --version
  -h                    --help
```

Here is an example error when I run pandocomatic with Pandoc 2 nightly:

```
👉  pandocomatic -b FastSlow.md
(3) + converting FastSlow.md 2 times:
(2)   - convert FastSlow.md -> FastSlow.tex
/Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_command.rb:149:in `block in pandoc': undefined method `reference_doc' for #<Paru::Pandoc:0x007ffb000e0f58> (NoMethodError)
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_command.rb:132:in `each'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_command.rb:132:in `pandoc'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_command.rb:92:in `convert_file'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_command.rb:59:in `run'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/command.rb:87:in `execute'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_multiple_command.rb:81:in `block in execute'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_multiple_command.rb:80:in `each'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/command/convert_file_multiple_command.rb:80:in `execute'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/lib/pandocomatic/pandocomatic.rb:108:in `run'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pandocomatic-0.1.4.3/bin/pandocomatic:3:in `<top (required)>'
	from /Users/ian/.rbenv/versions/2.4.1/bin/pandocomatic:23:in `load'
	from /Users/ian/.rbenv/versions/2.4.1/bin/pandocomatic:23:in `<main>'
```

Nightly download: https://github.com/pandoc-extras/pandoc-nightly/releases

**Comment by iandol** [comment]
OK, on closer examination it seems that Paru also needs to be modified to handle the new optios, as I see it uses a YAML file with the options: https://github.com/htdebeer/paru/blob/master/lib/paru/pandoc_options.yaml — I wonder whether you should have two YAML files for 1.X and 2.X and choose them based on the pandoc version string which you do extract when initialising the Pandoc class?

**Comment by htdebeer** [comment]
Yes, that is a good idea! I've added the `Paru::Pandoc::info` anyway and I can use it to determine the pandoc / pandoc types version used and depending on which version read a different version of the pandoc_options.yaml file. I can introduce similar pandocomatic_options.yaml file for pandocomatic.

That's the fun thing about Ruby and metaprogramming, I can determine what things to support run-time rather than compile time. Depending on the weather, I'll investigate it this weekend or the next.

**Comment by htdebeer** [comment]
I've updated pandocomatic (and paru) to support multiple versions of pandoc. Set the environemnt variable `PARU_PANDOC_PATH` to change the pandoc executable to use.
