### ISSUE TITLE
getcwd: cannot access parent directories: Operation not permitted

### ISSUE THREAD

**Issue by plbt5** [htdebeer/pandocomatic#94]
Installed scrivomatic according to your installation guide and verified its correct installation with your excellent Workflow example. Downloaded your "live" Pandoc data directory contents (default location: `$HOME/.local/share/pandoc/` on macOS) and verified correct operation. Next step is to prepare a document of myself in Scrivener and apply scrivomatic; for that I followed the Readme.md in `https://github.com/iandol/scrivomatic`

Intermediary generated markdown (only the yaml frontmatter):

~~~
---
# Standard Scrivener+Pandoc Project YAML metadata
# IMPORTANT: YAML configuration files use SPACES for indentation to define structure, remember to straighten any smart quotes, and don't capitalise metadata keys like "author" or "title", they must be lowercase!
title: "Consolidating Semantic Interoperability in
Contemporary Architectural Paradigms"
author:
  - name: Jonny Doy
    affiliation: 1
    correspondence: Jdoy@university.nl
    equal_contributor: true
  - name: His Colleague
    affiliation: 2
    equal_contributor: true   
  - name: His co-promoter   
    affiliation: 3     
  - name: His Promoter     
    affiliation: 1  
institute:
  - ^1^ First University of Technology (FUT), The Netherlands.
  - ^2^ Ministry of Some Matters, The Netherlands.
  - ^3^ Second University of Physics (SUP), The Netherlands.
keywords:
  - software architectures
  - semantic architectures
  - semantics
  - pragmatics
  - ontology
  - semantic principles
compiled: 10/08/2021
date: Tuesday, 10 August 2021
comments: "To err is human; … err?"
# Select which templates pandocomatic will use
# you can enter overrides to the templates here as well
pandocomatic_:
  use-template:
    - paper-with-refs-latex
  postprocessors:
    - postprocessors/check_links.sh


# Introduction #

When specifying semantics in software 
~~~

So far seems ok, but then pandocomatic kicks in, and I presume there are autorisation issues, ("`cannot access parent directories: Operation not permitted`") as follows:

~~~
=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.29 Report @ 2021-08-10 17:29:59 +0200 ===
=== ------------------------------------------------------ ===
 Working directory: 
 Initiating with Ruby 2.6.3
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="2021_swSemantics.md", output=nil, to=nil, yaml=nil, command="pandocomatic", envpath="/Users/paulbrandt/bin:/Library/TeX/texbin:/usr/local/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/paulbrandt/bin:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.14.1
---pandocomatic: /usr/local/bin/pandocomatic | V: 
---ruby: /usr/bin/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
---rbenv versions:
---gem: /usr/bin/gem
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /usr/local/bin/pandocomatic --debug 2021_swSemantics.md 
::: shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
::: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
::: job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
::: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:80:in `pwd': Operation not permitted - getcwd (Errno::EPERM)
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:80:in `lockfile_contents'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:68:in `lockfile_version'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:22:in `bundler_version_with_reason'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:7:in `bundler_version'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:39:in `compatible?'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1042:in `block in find_by_path'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1041:in `each'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1041:in `find'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1041:in `find_by_path'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:212:in `try_activate'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:14:in `<top (required)>'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/configuration.rb:21:in `<module:Pandocomatic>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/configuration.rb:19:in `<top (required)>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/cli.rb:23:in `require_relative'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/cli.rb:23:in `<module:Pandocomatic>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/cli.rb:19:in `<top (required)>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/pandocomatic.rb:29:in `require_relative'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/pandocomatic.rb:29:in `<module:Pandocomatic>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/pandocomatic.rb:19:in `<top (required)>'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/bin/pandocomatic:2:in `<top (required)>'
::: 	from /usr/local/bin/pandocomatic:23:in `load'
::: 	from /usr/local/bin/pandocomatic:23:in `<main>'
::: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/psych.so (LoadError)
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:14:in `<top (required)>'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/configuration.rb:21:in `<module:Pandocomatic>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/configuration.rb:19:in `<top (required)>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/cli.rb:23:in `require_relative'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/cli.rb:23:in `<module:Pandocomatic>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/cli.rb:19:in `<top (required)>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/pandocomatic.rb:29:in `require_relative'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/pandocomatic.rb:29:in `<module:Pandocomatic>'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/lib/pandocomatic/pandocomatic.rb:19:in `<top (required)>'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from /Library/Ruby/Gems/2.6.0/gems/pandocomatic-0.2.7.5/bin/pandocomatic:2:in `<top (required)>'
::: 	from /usr/local/bin/pandocomatic:23:in `load'
::: 	from /usr/local/bin/pandocomatic:23:in `<main>'
:: exit status: pid 15273 exit 1

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic --debug 2021_swSemantics.md !!!
~~~

What did I do wrong?
Thank you in advance

Paul

**Comment by htdebeer** [comment]
I am not sure you did anything wrong with your use of pandocomatic. As far as I understand your stack trace, your system has trouble executing the "getcwd" command while loading Ruby's YAML library. 

If I search for the error message `shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted` on the Internet, I get some hits. I am not sure they are very helpful thoug. Some suggest that the issue might be caused by [trying to read from a directory that does not exist anymore](https://stackoverflow.com/questions/29396928/shell-init-error-retrieving-current-directory-getcwd-the-usual-fixes-do-not/41704858), somehow. Or that [Mac OS needs special privileges](https://stackoverflow.com/questions/61510765/error-in-jenkins-mac-catalina-cannot-access-parent-directories-operation-not) to access certain system directories.

Does setting these privileges in Mac OS help? 

If not, can you try to create a minimal example where you encounter this issue? Maybe then I can also reproduce it on Linux?

**Comment by plbt5** [comment]
I can't derive the particular directory that is referred to in the error meesage with `current directory` so I can't verify its (non-)existence. 

I have modified priviliges for `/bin/sh`, and `/bin/bash`. This did not help.

In order to further investigate, I started the bash-cli for pandocomatic. This to remove any Scrivomatic influence. To my surprise, another error came up  that I have issued as #95 

I suggest to first investigate that one before continuing with this one.

**Comment by iandol** [comment]
@plbt5 -- did you ever resolve this error? I've never seen it on macOS, but if you have a minimal test case I can try to reproduce it.

**Comment by plbt5** [comment]
@iandol -- Nope, this is still a problem. 

As a sidenote and following on my previous report, I realised that although I extended the privileges for `/bin/sh` and `/bin/bash` I totally forgot to extend the privileges for `terminal` *duh*. Unfortunately this was no success either.
 
From the `Scrivomatic.log` I learn that Scrivomatic insists on using `/System/Library/Frameworks/Ruby.framework/Versions/2.6`, as follows:

- I found this related issue on "[pod init](https://stackoverflow.com/questions/61979388/pod-init-returns-operation-not-permitted-getcwd-errnoeperm)" at stackoverflow. And I followed their suggestion to go away from macOS system ruby and install ruby v3.0.2. 
- Just running Scrivomatic doesn't change anything - the log is identical. 
- I investigated which ruby is used in the shell: `ruby -v` produced
  - `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin21]`
- `which -a ruby` produced
  - `/Users/paulbrandt/.rvm/rubies/ruby-3.0.2/bin/ruby`
  - `/usr/bin/ruby`
- I enforced, as far as possible, the use of ruby3 by: `ruby /Users/paulbrandt/.scripts/scrivomatic.rb -I ...`
  - This changed the log significantly. As opposed to many messages about the `getcwd` issue, only one error is produced about `find_spec_for_exe': can't find gem pandocomatic`
  - The interesting part of the logged error (see below) is that that error is produced by -again- `/System/Library/Frameworks/Ruby.framework/Versions/2.6`. 
  - Hence my conclusion that Scrivomatic insists on ruby 2.6, or that is somehow falls back to it.

Is there something you can do about this at your end? Thanks in advance.

When running:
`ruby /Users/paulbrandt/.scripts/scrivomatic.rb -i 2021_swSemantics.md -y ./pandocomatic.yaml -l -v 2>&1 >>scrivomatic.log`
the log file presents:
```
=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.29 Report @ 2021-12-10 21:21:54 +0100 ===
=== ------------------------------------------------------ ===
 Working directory: /Users/paulbrandt/Documents/Promotieonderzoek/Papers/2021_swSem
 Initiating with Ruby 3.0.2
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="2021_swSemantics.md", output=nil, to=nil, yaml="./pandocomatic.yaml", command="pandocomatic", envpath="/Users/paulbrandt/bin:/Library/TeX/texbin:/usr/local/bin:/Users/paulbrandt/.local/bin:/Users/paulbrandt/.rvm/wrappers/default", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/paulbrandt/bin:/Library/TeX/texbin:/usr/local/bin:/Users/paulbrandt/.local/bin:/Users/paulbrandt/.rvm/wrappers/default:/Users/paulbrandt/.rvm/gems/ruby-3.0.2/bin:/Users/paulbrandt/.rvm/gems/ruby-3.0.2@global/bin:/Users/paulbrandt/.rvm/rubies/ruby-3.0.2/bin:/Users/paulbrandt/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/paulbrandt/.local/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.14.2
---pandocomatic: /usr/local/bin/pandocomatic | V: 
---ruby: /Users/paulbrandt/.rvm/wrappers/default/ruby | V: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin21]
---rbenv versions:
---rvm: /Users/paulbrandt/.rvm/bin/rvm
---gem: /Users/paulbrandt/.rvm/wrappers/default/gem
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /usr/local/bin/pandocomatic -c ./pandocomatic.yaml --debug 2021_swSemantics.md 
::: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem pandocomatic (>= 0.a) with executable pandocomatic (Gem::GemNotFoundException)
::: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
::: 	from /usr/local/bin/pandocomatic:23:in `<main>'
:: exit status: pid 77744 exit 1

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic -c ./pandocomatic.yaml --debug 2021_swSemantics.md !!!

```

**Comment by iandol** [comment]
@plbt5 — I switched from `rvm` to prefer `rbenv` as I found it less complex and thus less buggy. I suspect the problem you have is something related to rvm… Note that you don’t have to install a newer Ruby, you could just completely remove rvm and install pandocomatic in the system ruby, that would simplify your moving parts, as long as your OS is up to date.

Scrivomatic just checks if rvm or rbenv is installed and adds them to the path, this is because by default Scrivener doesn’t use the user’s shell environment.

**Comment by iandol** [comment]
Note here is the output from my macOS system, where `pandocomatic` + `paru` all work without issue. The important point is that the `pandocomatic` path and `ruby` path's are consistently directed to the `rbenv` location (which is not the case for you I think as pandocomatic is in `/usr/local` but ruby is in the `rvm` . Note I use homebrew to install `pandoc` and `rbenv`, then use `rbenv` to install `ruby` and switch between the system and `rbenv` versions. `rbenv` has a `default-gems` plugin so you can even make sure pandocomatic and paru are always installed with every new `ruby` automagically.

```
=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.30 Report @ 2021-12-02 09:02:28 +0100 ===
=== ------------------------------------------------------ ===
 Running shell: /bin/zsh
 Working directory: /Users/ian/Desktop/Compile-mmd
 Initiating with Ruby 2.6.8
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="Haoyu\\ letter.md", output=nil, to=nil, yaml=nil, command="pandocomatic", envpath="/Users/ian/bin:/Users/ian/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin", build=true, cleanup=true, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/ian/bin:/Users/ian/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.16.2
---pandocomatic: /Users/ian/.rbenv/shims/pandocomatic | V: 0.3.α
---ruby: /Users/ian/.rbenv/shims/ruby | V: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
---rbenv versions:
  system
* 3.0.2 (set by /Users/ian/.rbenv/version)
---rbenv: /usr/local/bin/rbenv
---gem: /Users/ian/.rbenv/shims/gem
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk
```

**Comment by plbt5** [comment]
@iandol Thanks for the suggestion. 

I have now a setup similar to yours where the pandocomatic path and ruby path's are consistently directed to the same rbenv location, and I can confirm that I don't run into the above issue anymore. 

I consider this issue resolved.
Thanks for your support.
